#!/usr/bin/env bash

set -e

STACK_NAME="rds-stack"
TEMPLATE_FILE="rds-template.yaml"
REGION="us-east-1"

echo "Deploying CloudFormation stack..."

aws cloudformation deploy \
    --stack-name "$STACK_NAME" \
    --template-file "$TEMPLATE_FILE" \
    --region "$REGION"

echo ""
echo "Deployment complete."
echo ""

aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query "Stacks[0].Outputs" \
    --output table